import { Component } from '@angular/core';

@Component({
  selector: 'app-edit',
  templateUrl: './edit.component.html',
  styleUrls: ['./edit.component.css']
})
export class EditComponent {
  nota = {
    titulo: 'Lorem Ipsum',
    conteudo: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In fringilla euismod metus laoreet tincidunt. Duis posuere hendrerit velit at pellentesque. Aenean blandit elit at tempus molestie. Quisque urna elit, volutpat ac ex at, accumsan facilisis odio. Maecenas sed maximus eros. Morbi vehicula orci sit amet placerat aliquam. Mauris semper dui ut libero cursus, vitae maximus mi varius. Nam eget augue felis. Nulla facilis Sed rutrum rhoncus urna id tincidunt. Donec eleifend velit nisi, ac vulputate mi placerat sit amet. Vivamus tristique, mi a sollicitudin pretium, lectus lacus posuere felis, vel mattis velit nisl a nisi. Proin vehicula urna ut lectus ultricies bibendum. Curabitur dignissim posuere velit at ullamcorper. Etiam sapien ex, bibendum ac neque a, lacinia congue lorem. Suspendisse posuere condimentum risus ac porta. Pellentesque ut metus urna. Vestibulum euismod sagittis turpis non commodo. Suspendisse ut faucibus felis. In maximus vel sapien vel pellentesque. Praesent posuere lacus sed mattis varius   Aliquam volutpat, ex ac viverra cursus, metus elit ornare sem, non rutrum nulla purus eu sem. Pellentesque sit amet nunc non nisi dapibus semper. Vestibulum bibendum felis ut enim pharetra, vitae porttitor purus iaculis. Morbi finibus leo nec sodales congue. Praesent interdum risus non neque sagittis, id lobortis augue ullamcorper. Curabitur viverra tortor quis tellus varius vulputate. Vestibulum rutrum, mi quis scelerisque condimentum, turpis orci accumsan dui, eu eleifend urna enim ut libero. Sed volutpat commodo nisl. Donec ultrices ultrices sem, in ornare ipsum aliquet sit amet. Integer sodales lorem at libero sollicitudin pharetra. Mauris id fringilla felis. Aliquam imperdiet auctor tortor, sed congue lectus faucibus non. Sed suscipit, lorem et dignissim euismod, metus mauris hendrerit massa, id blandit velit est et ipsum. Mauris congue odio sollicitudin imperdiet hendrerit. Nullam quis lacus at dui aliquam interdum.  Nunc tellus risus, tincidunt et egestas eu, ultricies id mauris. Proin tincidunt sed elit in maximus. Maecenas ut massa mauris. Nulla facilisi. Phasellus vitae pharetra mauris. Phasellus non libero laoreet, accumsan purus eget, luctus felis. Ut sem augue, sodales volutpat nibh id, tempor condimentum ligula.  Aliquam a lorem facilisis, maximus felis et, imperdiet dolor. Mauris aliquam sem ut massa egestas maximus. Nam facilisis consequat lectus, eu tristique justo. Cras condimentum dolor sed sapien hendrerit eleifend. Quisque felis lorem, ullamcorper quis nunc eget, lobortis tincidunt tortor. Pellentesque tincidunt accumsan eleifend. Ut condimentum elit nec arcu mattis luctus. Nullam sodales, orci posuere efficitur laoreet, erat nulla ornare sem, ut congue libero ligula tempor arcu. Quisque ut fermentum leo, non sagittis dui.'
  }
}
